# Generated by Django 4.1.2 on 2022-10-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('QB', 'Quarter Back'), ('RB', 'Running Back'), ('WR', 'Wide Receiver')], max_length=2)),
            ],
        ),
    ]
