# Generated by Django 4.2 on 2023-05-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "player_scraping",
            "0003_remove_team_roster_remove_team_roster_history_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerstat",
            old_name="qb_points",
            new_name="week",
        ),
        migrations.RemoveField(
            model_name="playerstat",
            name="game",
        ),
        migrations.RemoveField(
            model_name="playerstat",
            name="position",
        ),
        migrations.RemoveField(
            model_name="playerstat",
            name="rb_points",
        ),
        migrations.RemoveField(
            model_name="playerstat",
            name="wr_points",
        ),
        migrations.AddField(
            model_name="playerstat",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="points",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
