# Generated by Django 4.2 on 2023-05-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_scraping", "0004_rename_qb_points_playerstat_week_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerstat",
            name="points",
        ),
        migrations.AddField(
            model_name="player",
            name="points",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
