# Generated by Django 4.2 on 2023-05-13 00:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("player_scraping", "0005_remove_playerstat_points_player_points"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="team",
            new_name="owner",
        ),
    ]
