# Generated by Django 4.2 on 2023-05-15 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("player_scraping", "0007_player_abr_team_player_full_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("week", models.IntegerField()),
                ("passingYards", models.IntegerField()),
                ("rushingAttempts", models.IntegerField()),
                ("rushingYards", models.IntegerField()),
                ("touchdowns", models.IntegerField()),
                ("receivingYards", models.IntegerField()),
                ("receptions", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="player",
            name="points",
        ),
        migrations.DeleteModel(
            name="PlayerStat",
        ),
        migrations.AddField(
            model_name="playerstats",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="player_scraping.player"
            ),
        ),
    ]
