# Generated by Django 4.2 on 2023-05-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_scraping", "0009_playerstat_delete_playerstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstat",
            name="activeGame",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerstat",
            name="points",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
