# Generated by Django 4.2 on 2023-05-18 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("player_scraping", "0010_playerstat_activegame_playerstat_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.IntegerField()),
                ("season", models.IntegerField()),
                ("team1_points", models.IntegerField()),
                ("team2_points", models.IntegerField()),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league",
                        to="player_scraping.league",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.IntegerField()),
                ("season", models.IntegerField()),
                ("points", models.IntegerField()),
                ("is_starting", models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name="team",
            old_name="starting_roster",
            new_name="roster",
        ),
        migrations.RemoveField(
            model_name="player",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="playerstat",
            name="activeGame",
        ),
        migrations.RemoveField(
            model_name="playerstat",
            name="passingYards",
        ),
        migrations.RemoveField(
            model_name="playerstat",
            name="receivingYards",
        ),
        migrations.RemoveField(
            model_name="playerstat",
            name="receptions",
        ),
        migrations.RemoveField(
            model_name="playerstat",
            name="rushingAttempts",
        ),
        migrations.RemoveField(
            model_name="playerstat",
            name="rushingYards",
        ),
        migrations.RemoveField(
            model_name="playerstat",
            name="touchdowns",
        ),
        migrations.RemoveField(
            model_name="team",
            name="backup_roster",
        ),
        migrations.RemoveField(
            model_name="team",
            name="schedule",
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="player_scraping.player"
            ),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="points",
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name="Game",
        ),
        migrations.AddField(
            model_name="teamroster",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="player_scraping.player"
            ),
        ),
        migrations.AddField(
            model_name="teamroster",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="player_scraping.team"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team1",
                to="player_scraping.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team2",
                to="player_scraping.team",
            ),
        ),
    ]
