# Generated by Django 4.2 on 2023-05-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "player_scraping",
            "0011_match_teamroster_rename_starting_roster_team_roster_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstat",
            name="points",
            field=models.IntegerField(null=True),
        ),
    ]
