# Generated by Django 4.2 on 2023-05-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("player_scraping", "0012_alter_playerstat_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstat",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="player_scraping.player",
            ),
        ),
    ]
