# Generated by Django 4.2 on 2023-05-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_scraping", "0013_alter_playerstat_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstat",
            name="points",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
