# Generated by Django 4.2 on 2023-05-27 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("player_scraping", "0014_alter_playerstat_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="player_scraping.league",
            ),
        ),
    ]
