# Generated by Django 4.2 on 2023-05-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player_scraping", "0015_team_league"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="team1_points",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="team2_points",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="teamroster",
            name="points",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
